"""tenancy people money floor plumbing schema

Revision ID: 36d3dc0d50cb
Revises: 
Create Date: 2026-09-14 08:39:45.540188

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '36d3dc0d50cb'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gyms',
    sa.Column('name', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('staff_users',
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('pin_hash', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('coaches',
    sa.Column('name', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('speciality', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('staff_user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('gym_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['gym_id'], ['gyms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['staff_user_id'], ['staff_users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coaches_gym_id'), 'coaches', ['gym_id'], unique=False)
    op.create_table('idempotency_keys',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('request_hash', sa.String(), nullable=False),
    sa.Column('response_status', sa.Integer(), nullable=False),
    sa.Column('response_body', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('gym_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['gym_id'], ['gyms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gym_id', 'key')
    )
    op.create_index(op.f('ix_idempotency_keys_gym_id'), 'idempotency_keys', ['gym_id'], unique=False)
    op.create_table('machines',
    sa.Column('name', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('area', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('gym_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['gym_id'], ['gyms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_machines_gym_id'), 'machines', ['gym_id'], unique=False)
    op.create_table('members',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('name_en', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('gym_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['gym_id'], ['gyms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gym_id', 'phone')
    )
    op.create_index(op.f('ix_members_gym_id'), 'members', ['gym_id'], unique=False)
    op.create_table('plans',
    sa.Column('name', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('price_usd', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('days', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('gym_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['gym_id'], ['gyms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plans_gym_id'), 'plans', ['gym_id'], unique=False)
    op.create_table('staff_gym_roles',
    sa.Column('staff_user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('gym_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['gym_id'], ['gyms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['staff_user_id'], ['staff_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('staff_user_id', 'gym_id')
    )
    op.create_index(op.f('ix_staff_gym_roles_gym_id'), 'staff_gym_roles', ['gym_id'], unique=False)
    op.create_index(op.f('ix_staff_gym_roles_staff_user_id'), 'staff_gym_roles', ['staff_user_id'], unique=False)
    op.create_table('attendance',
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('gym_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['gym_id'], ['gyms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gym_id', 'member_id', 'date')
    )
    op.create_index(op.f('ix_attendance_gym_id'), 'attendance', ['gym_id'], unique=False)
    op.create_index(op.f('ix_attendance_member_id'), 'attendance', ['member_id'], unique=False)
    op.create_table('bookings',
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.Column('coach_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('gym_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['coach_id'], ['coaches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['gym_id'], ['gyms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookings_gym_id'), 'bookings', ['gym_id'], unique=False)
    op.create_index(op.f('ix_bookings_member_id'), 'bookings', ['member_id'], unique=False)
    op.create_table('check_ins',
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('gym_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['gym_id'], ['gyms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_check_ins_gym_id'), 'check_ins', ['gym_id'], unique=False)
    op.create_index(op.f('ix_check_ins_member_id'), 'check_ins', ['member_id'], unique=False)
    op.create_table('classes',
    sa.Column('title', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('coach_id', sa.UUID(), nullable=False),
    sa.Column('weekdays', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('time', sa.String(), nullable=False),
    sa.Column('duration_min', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('gym_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['coach_id'], ['coaches.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['gym_id'], ['gyms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_classes_gym_id'), 'classes', ['gym_id'], unique=False)
    op.create_table('member_profiles',
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.Column('goal', sa.String(), nullable=False),
    sa.Column('level', sa.String(), nullable=False),
    sa.Column('height_cm', sa.Integer(), nullable=False),
    sa.Column('weight_kg', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.Column('body_fat', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('injuries', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('days_per_week', sa.Integer(), nullable=False),
    sa.Column('job', sa.String(), nullable=False),
    sa.Column('sleep_hours', sa.Numeric(precision=3, scale=1), nullable=False),
    sa.Column('weight_trend', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('gym_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['gym_id'], ['gyms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('member_id')
    )
    op.create_index(op.f('ix_member_profiles_gym_id'), 'member_profiles', ['gym_id'], unique=False)
    op.create_table('payments',
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.Column('amount_usd', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('method', sa.String(), nullable=False),
    sa.Column('recorded_by_staff_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('gym_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['gym_id'], ['gyms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recorded_by_staff_id'], ['staff_users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_gym_id'), 'payments', ['gym_id'], unique=False)
    op.create_index(op.f('ix_payments_member_id'), 'payments', ['member_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('gym_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['gym_id'], ['gyms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_gym_id'), 'subscriptions', ['gym_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_member_id'), 'subscriptions', ['member_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscriptions_member_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_gym_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_payments_member_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_gym_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_member_profiles_gym_id'), table_name='member_profiles')
    op.drop_table('member_profiles')
    op.drop_index(op.f('ix_classes_gym_id'), table_name='classes')
    op.drop_table('classes')
    op.drop_index(op.f('ix_check_ins_member_id'), table_name='check_ins')
    op.drop_index(op.f('ix_check_ins_gym_id'), table_name='check_ins')
    op.drop_table('check_ins')
    op.drop_index(op.f('ix_bookings_member_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_gym_id'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_index(op.f('ix_attendance_member_id'), table_name='attendance')
    op.drop_index(op.f('ix_attendance_gym_id'), table_name='attendance')
    op.drop_table('attendance')
    op.drop_index(op.f('ix_staff_gym_roles_staff_user_id'), table_name='staff_gym_roles')
    op.drop_index(op.f('ix_staff_gym_roles_gym_id'), table_name='staff_gym_roles')
    op.drop_table('staff_gym_roles')
    op.drop_index(op.f('ix_plans_gym_id'), table_name='plans')
    op.drop_table('plans')
    op.drop_index(op.f('ix_members_gym_id'), table_name='members')
    op.drop_table('members')
    op.drop_index(op.f('ix_machines_gym_id'), table_name='machines')
    op.drop_table('machines')
    op.drop_index(op.f('ix_idempotency_keys_gym_id'), table_name='idempotency_keys')
    op.drop_table('idempotency_keys')
    op.drop_index(op.f('ix_coaches_gym_id'), table_name='coaches')
    op.drop_table('coaches')
    op.drop_table('staff_users')
    op.drop_table('gyms')
    # ### end Alembic commands ###
