"""auth tables: refresh tokens and member login codes

Revision ID: 4a54ba2b0a0a
Revises: 6290203bb295
Create Date: 2026-09-14 08:47:53.912687

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '4a54ba2b0a0a'
down_revision: str | Sequence[str] | None = '6290203bb295'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refresh_tokens',
    sa.Column('jti', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('subject_type', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('gym_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['gym_id'], ['gyms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jti')
    )
    op.create_index(op.f('ix_refresh_tokens_gym_id'), 'refresh_tokens', ['gym_id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_subject_id'), 'refresh_tokens', ['subject_id'], unique=False)
    op.create_table('member_login_codes',
    sa.Column('gym_id', sa.UUID(), nullable=False),
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('code_hash', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['gym_id'], ['gyms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_member_login_codes_gym_id'), 'member_login_codes', ['gym_id'], unique=False)
    op.create_index(op.f('ix_member_login_codes_member_id'), 'member_login_codes', ['member_id'], unique=False)
    op.create_index(op.f('ix_member_login_codes_phone'), 'member_login_codes', ['phone'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_member_login_codes_phone'), table_name='member_login_codes')
    op.drop_index(op.f('ix_member_login_codes_member_id'), table_name='member_login_codes')
    op.drop_index(op.f('ix_member_login_codes_gym_id'), table_name='member_login_codes')
    op.drop_table('member_login_codes')
    op.drop_index(op.f('ix_refresh_tokens_subject_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_gym_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    # ### end Alembic commands ###
