"""member content tables: videos, food entries, progress photos

Revision ID: b199dcb1520a
Revises: 67eb54d688f0
Create Date: 2026-09-19 09:14:10.734475

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b199dcb1520a'
down_revision: str | Sequence[str] | None = '67eb54d688f0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('videos',
    sa.Column('title', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('muscle_group', sa.String(), nullable=False),
    sa.Column('equipment', sa.String(), nullable=False),
    sa.Column('seconds', sa.Integer(), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_by_staff_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('gym_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_staff_id'], ['staff_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['gym_id'], ['gyms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_videos_gym_id'), 'videos', ['gym_id'], unique=False)
    op.create_table('food_entries',
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('kcal', sa.Integer(), nullable=False),
    sa.Column('protein', sa.Integer(), nullable=False),
    sa.Column('carbs', sa.Integer(), nullable=False),
    sa.Column('fat', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('photo_key', sa.String(), nullable=True),
    sa.Column('estimate', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('gym_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['gym_id'], ['gyms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_food_entries_gym_id'), 'food_entries', ['gym_id'], unique=False)
    op.create_index(op.f('ix_food_entries_member_id'), 'food_entries', ['member_id'], unique=False)
    op.create_table('progress_photos',
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('photo_key', sa.String(), nullable=False),
    sa.Column('shared_with_coach', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('gym_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['gym_id'], ['gyms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_progress_photos_gym_id'), 'progress_photos', ['gym_id'], unique=False)
    op.create_index(op.f('ix_progress_photos_member_id'), 'progress_photos', ['member_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_progress_photos_member_id'), table_name='progress_photos')
    op.drop_index(op.f('ix_progress_photos_gym_id'), table_name='progress_photos')
    op.drop_table('progress_photos')
    op.drop_index(op.f('ix_food_entries_member_id'), table_name='food_entries')
    op.drop_index(op.f('ix_food_entries_gym_id'), table_name='food_entries')
    op.drop_table('food_entries')
    op.drop_index(op.f('ix_videos_gym_id'), table_name='videos')
    op.drop_table('videos')
    # ### end Alembic commands ###
