"""billing columns on gyms

Revision ID: d2c2cd8e06c7
Revises: b630206a601c
Create Date: 2026-09-23 07:33:41.183394

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd2c2cd8e06c7'
down_revision: str | Sequence[str] | None = 'b630206a601c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gyms', sa.Column('billing_status', sa.String(), server_default='trial', nullable=False))
    op.add_column('gyms', sa.Column('monthly_usd', sa.Numeric(precision=8, scale=2, asdecimal=False), nullable=True))
    op.add_column('gyms', sa.Column('paid_through', sa.Date(), nullable=True))
    op.add_column('gyms', sa.Column('billing_notes', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gyms', 'billing_notes')
    op.drop_column('gyms', 'paid_through')
    op.drop_column('gyms', 'monthly_usd')
    op.drop_column('gyms', 'billing_status')
    # ### end Alembic commands ###
