"""add pin_reset_at to staff_users

Revision ID: dbc5c9b72f2a
Revises: 3bf5ae412866
Create Date: 2026-09-15 16:38:54.599794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbc5c9b72f2a'
down_revision: Union[str, Sequence[str], None] = '3bf5ae412866'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staff_users', sa.Column('pin_reset_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('staff_users', 'pin_reset_at')
    # ### end Alembic commands ###
