"""ai plan drafts and daily kcal target

Revision ID: ef514a1883f9
Revises: 42b10555715a
Create Date: 2026-09-22 15:39:37.549021

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ef514a1883f9'
down_revision: str | Sequence[str] | None = '42b10555715a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_plan_drafts',
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('headline', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('body', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reason', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('decided_by_staff_id', sa.UUID(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('original', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('gym_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['decided_by_staff_id'], ['staff_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['gym_id'], ['gyms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_plan_drafts_gym_id'), 'ai_plan_drafts', ['gym_id'], unique=False)
    op.create_index(op.f('ix_ai_plan_drafts_member_id'), 'ai_plan_drafts', ['member_id'], unique=False)
    op.add_column('member_profiles', sa.Column('daily_kcal_target', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('member_profiles', 'daily_kcal_target')
    op.drop_index(op.f('ix_ai_plan_drafts_member_id'), table_name='ai_plan_drafts')
    op.drop_index(op.f('ix_ai_plan_drafts_gym_id'), table_name='ai_plan_drafts')
    op.drop_table('ai_plan_drafts')
    # ### end Alembic commands ###
