import { Link } from 'react-router-dom'
import { useTranslation } from 'react-i18next'
import { buttonClass } from '@/components/ui/Button'
import { Icon, type IconName } from '@/components/ui/Icon'
import { API_URL } from '@/data/client'
import { waLink } from '@/lib/whatsapp'
import { cn } from '@/lib/cn'
import type { Lang } from '@/i18n'

/**
 * The public front door: what AIGym does, shown with the real screens rather
 * than described. Everything a visitor sees here is a screenshot of the app
 * running on the seeded gym, regenerated by `scripts/landing-shots.mjs` — a
 * gym owner who has been sold a mockup notices on day one.
 *
 * No pricing and no signup form. Gyms are provisioned by the operator after a
 * conversation (decision 34), and a public form would be an abuse surface
 * serving a channel this business does not use.
 */

/** Optional, set per deployment. With no number configured the WhatsApp
 * call-to-action does not render at all — a dead contact link is worse than
 * none, and inventing a number is not an option. */
const CONTACT_PHONE = import.meta.env.VITE_CONTACT_PHONE as string | undefined

/** One section each, in the order a gym owner cares about: their money
 * first, then their members, then how the thing gets installed. `shot` is
 * the file stem under public/landing/; the language suffix is chosen at
 * render time so an Arabic visitor is shown the Arabic product, not an
 * English one with Arabic copy underneath. */
const FEATURES = [
  { key: 'dues', shot: 'home' },
  { key: 'proof', shot: 'insights' },
  { key: 'lapsed', shot: 'lapsed' },
  { key: 'floor', shot: 'session', wide: true },
  { key: 'member', shot: 'member' },
  { key: 'assistant', shot: 'chat' },
  { key: 'import', shot: 'import' },
] as const

const BUILT: { key: string; icon: IconName }[] = [
  { key: 'power', icon: 'bolt' },
  { key: 'light', icon: 'check' },
  { key: 'lang', icon: 'chat' },
  { key: 'whatsapp', icon: 'whatsapp' },
  { key: 'privacy', icon: 'lock' },
]

function Shot({ stem, lang, alt, wide }: { stem: string; lang: Lang; alt: string; wide?: boolean }) {
  return (
    <img
      src={`/landing/${stem}-${lang}.webp`}
      alt={alt}
      width={wide ? 1120 : 520}
      height={wide ? 840 : 1125}
      // Seven screenshots is more than the fold needs. They are also
      // deliberately left out of the service worker's precache — an offline
      // shell should hold the app, not its advertising.
      loading="lazy"
      decoding="async"
      className={cn(
        'border-chrome/10 mx-auto h-auto w-full rounded-2xl border shadow-xl',
        wide ? 'max-w-xl' : 'max-w-[16rem]',
      )}
    />
  )
}

export function Landing() {
  const { t, i18n } = useTranslation()
  const lang = i18n.language as Lang

  // With no API configured there is no login to send anyone to — mock mode
  // has never gated these routes (see RequireStaff in App.tsx), so the
  // buttons open the surfaces directly and the prototype stays a prototype.
  const staffTarget = API_URL ? '/staff/login' : '/manager'
  const memberTarget = API_URL ? '/login' : '/member'

  return (
    <div className="bg-canvas min-h-full">
      <header className="bg-chrome">
        <div className="mx-auto flex min-h-16 max-w-5xl items-center justify-between gap-3 px-4">
          <div className="flex min-w-0 items-center gap-3">
            <img src="/logo.png" alt="" width={36} height={36} className="size-9 rounded-lg" />
            <span className="text-brand text-sm font-extrabold">{t('common.appName')}</span>
          </div>
          <div className="flex items-center gap-2">
            <button
              type="button"
              onClick={() => void i18n.changeLanguage(lang === 'ar' ? 'en' : 'ar')}
              className="min-h-11 rounded-xl border border-white/25 px-3 text-sm font-bold text-white"
            >
              {lang === 'ar' ? 'EN' : 'ع'}
            </button>
            <Link
              to={staffTarget}
              className="inline-flex min-h-11 items-center rounded-xl border border-white/25 px-3 text-sm font-bold text-white"
            >
              {t('landing.staffSignIn')}
            </Link>
          </div>
        </div>
      </header>

      {/* Hero. Yellow stays identity here too: the block behind the headline
          and one action, never a status and never decoration. */}
      <section className="bg-chrome relative overflow-hidden">
        {/* Identity, not decoration — and only where there is room for it.
            At 390px this square lands squarely under the headline, and white
            on #f9e54c fails contrast badly enough to make the sentence
            unreadable. The yellow band directly below carries the colour on
            a phone instead. */}
        <div
          aria-hidden
          className="bg-brand/90 pointer-events-none absolute -top-32 end-[-20%] hidden size-96 rotate-45 lg:block"
        />
        <div className="relative mx-auto max-w-5xl space-y-5 px-4 pb-12 pt-8">
          <p className="text-brand text-xs font-bold uppercase">{t('landing.eyebrow')}</p>
          <h1 className="max-w-2xl text-3xl font-extrabold leading-tight text-white sm:text-5xl">
            {t('landing.headline')}
          </h1>
          <p className="max-w-xl text-base text-white/70">{t('landing.sub')}</p>
          <div className="flex flex-wrap gap-3">
            <a href="#features" className={buttonClass('brand', 'lg')}>
              {t('landing.seeInside')}
            </a>
            {CONTACT_PHONE ? (
              <a
                href={waLink(CONTACT_PHONE, t('landing.waMessage'))}
                target="_blank"
                rel="noreferrer"
                className="inline-flex min-h-tap-lg items-center justify-center gap-2 rounded-xl border border-white/25 px-6 text-base font-semibold text-white"
              >
                <Icon name="whatsapp" size={18} />
                {t('landing.talk')}
              </a>
            ) : null}
          </div>
        </div>
      </section>

      {/* The offer, stated once and in its own band so it is not read as one
          feature among seven. Black on yellow — the highest-contrast pair in
          the palette, and the gym's own flyer colours. */}
      <section className="bg-brand text-chrome">
        <div className="mx-auto max-w-5xl space-y-2 px-4 py-8">
          <p className="text-xs font-bold uppercase opacity-70">{t('landing.guaranteeTitle')}</p>
          <p className="max-w-3xl text-xl font-extrabold leading-snug sm:text-2xl">
            {t('landing.guarantee')}
          </p>
        </div>
      </section>

      <section id="features" className="mx-auto max-w-5xl space-y-14 px-4 py-14">
        {FEATURES.map((feature, i) => {
          const title = t(`landing.features.${feature.key}.title`)
          return (
            <div
              key={feature.key}
              className={cn(
                'flex flex-col items-center gap-6 sm:flex-row sm:items-center sm:gap-10',
                // Alternating sides read as a rhythm rather than a list.
                // flex-row-reverse mirrors with `dir`, so this is correct in
                // both languages without a second rule.
                i % 2 === 1 && 'sm:flex-row-reverse',
              )}
            >
              <div className="flex-1 space-y-3">
                <h2 className="text-2xl font-extrabold leading-tight">{title}</h2>
                <p className="text-muted max-w-md leading-relaxed">
                  {t(`landing.features.${feature.key}.body`)}
                </p>
              </div>
              <div className="w-full flex-1">
                <Shot stem={feature.shot} lang={lang} alt={title} wide={'wide' in feature} />
              </div>
            </div>
          )
        })}
      </section>

      <section className="bg-surface border-line border-t">
        <div className="mx-auto max-w-5xl space-y-6 px-4 py-14">
          <h2 className="text-2xl font-extrabold">{t('landing.builtTitle')}</h2>
          <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
            {BUILT.map((item) => (
              <div key={item.key} className="border-line space-y-2 rounded-2xl border p-4">
                {/* Neutral ink, never green/amber/red — those mean payment
                    state and nothing else, marketing page included. */}
                <span className="text-ink">
                  <Icon name={item.icon} />
                </span>
                <h3 className="font-bold">{t(`landing.built.${item.key}.title`)}</h3>
                <p className="text-muted text-sm leading-relaxed">
                  {t(`landing.built.${item.key}.body`)}
                </p>
              </div>
            ))}
          </div>
        </div>
      </section>

      <footer className="bg-chrome">
        <div className="mx-auto max-w-5xl space-y-4 px-4 py-12">
          <h2 className="text-xl font-extrabold text-white">{t('landing.closingTitle')}</h2>
          <div className="flex flex-wrap gap-3">
            <Link to={staffTarget} className={buttonClass('brand', 'lg')}>
              {t('landing.staffSignIn')}
            </Link>
            <Link
              to={memberTarget}
              className="inline-flex min-h-tap-lg items-center justify-center rounded-xl border border-white/25 px-6 text-base font-semibold text-white"
            >
              {t('landing.memberSignIn')}
            </Link>
          </div>
          <p className="text-xs text-white/40">{t('landing.footerNote')}</p>
        </div>
      </footer>
    </div>
  )
}
